# Generated by Django 4.2.4 on 2023-08-24 05:52

import administrator.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeHeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='heading', max_length=255)),
                ('tagline', models.CharField(default='tagline', max_length=255)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=administrator.models.HomeHeroBanner.thumb_upload)),
                ('slug', models.CharField(default='slug', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=255)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[1920, 1080], upload_to=administrator.models.Testimonials.thumb_upload)),
                ('content', models.TextField(default='Lorem Ipsum is simply dummy text of the printing and typesetting industry.')),
            ],
        ),
    ]
