# Generated by Django 4.2.4 on 2023-08-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_homeherobanner_testimonials'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonials',
            name='designation',
            field=models.CharField(default='designation', max_length=255),
        ),
    ]
