# Generated by Django 4.2.4 on 2023-08-24 09:48

import administrator.models
from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_testimonials_designation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonials',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to=administrator.models.Testimonials.thumb_upload),
        ),
    ]
