# Generated by Django 4.2.4 on 2023-08-25 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_alter_testimonials_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_tag', models.TextField()),
                ('other_contet', models.TextField()),
            ],
        ),
    ]
