# Generated by Django 4.2.4 on 2023-09-18 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_alter_blogs_options_blogs_content_blogs_created_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
