# Generated by Django 4.2.4 on 2023-09-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='title',
            field=models.CharField(blank=True, default='title', max_length=200),
        ),
    ]
