# Generated by Django 4.2.4 on 2023-09-18 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0013_alter_filter_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filter',
            name='title',
        ),
    ]
