# Generated by Django 4.2.4 on 2023-09-18 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_remove_filter_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.filterparent'),
        ),
    ]
