# Generated by Django 4.2.4 on 2023-09-18 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_filter_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Filter',
        ),
    ]
