# Generated by Django 4.2.4 on 2023-09-18 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_filter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('requirements', models.CharField(choices=[('find_property', 'Find a Property'), ('list_property', 'List a Property')], max_length=20)),
                ('message', models.TextField()),
                ('created_on', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
