# Generated by Django 4.2.4 on 2023-09-20 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0018_contactform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='category',
            field=models.CharField(choices=[('article', 'Articles'), ('blogs', 'Blogs'), ('news', 'News')], default='blogs', max_length=20),
        ),
    ]
